### SIGNUP
POST http://localhost:3000/signup
Content-Type: application/json

{
  "fullname": "Phong",
  "email": "phong@gmail.com",
  "password": "123456",
  "username": "phongdz"
}

### SIGNIN
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "phong@gmail.com",
  "password": "123456"
}